package services_test

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"io"
	"regexp"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock" // Only if other mocks are needed, not for ConferenceService directly
	"github.com/user/agbaravoip_golang/internal/domain"
	"github.com/user/agbaravoip_golang/internal/services"
	"github.com/user/agbaravoip_golang/internal/utils" // For GenerateSID in GetOrCreate
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
)

// Helper to setup mock DB for GORM
func setupConferenceMockDB(t *testing.T) (*gorm.DB, sqlmock.Sqlmock) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}

	gormDB, err := gorm.Open(postgres.New(postgres.Config{
		Conn: db,
	}), &gorm.Config{
		Logger: gormlogger.Default.LogMode(gormlogger.Silent),
	})
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening gorm database", err)
	}
	return gormDB, mock
}

// Helper for logger
func newConferenceTestLogger() *logrus.Logger {
	logger := logrus.New()
	logger.SetOutput(io.Discard)
	return logger
}

var now = time.Now().UTC() // For consistent timestamps in tests

// --- Conference Method Tests ---

func TestConferenceService_GetConferenceBySID_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	confSID := "CFtestSID"
	expectedConf := &domain.Conference{SID: confSID, FriendlyName: "TestRoom"}

	rows := sqlmock.NewRows([]string{"id", "sid", "account_sid", "friendly_name", "status", "start_time", "end_time", "created_at", "updated_at"}).
		AddRow(1, confSID, "AC123", "TestRoom", domain.ConferenceStatusInProgress, now, nil, now, now)

	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conferences" WHERE sid = $1`)).
		WithArgs(confSID).
		WillReturnRows(rows)

	conf, err := service.GetConferenceBySID(context.Background(), confSID)
	assert.NoError(t, err)
	assert.NotNil(t, conf)
	assert.Equal(t, expectedConf.SID, conf.SID)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_GetConferenceBySID_NotFound(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	confSID := "CFnonexistent"
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conferences" WHERE sid = $1`)).
		WithArgs(confSID).
		WillReturnError(gorm.ErrRecordNotFound)

	conf, err := service.GetConferenceBySID(context.Background(), confSID)
	assert.Error(t, err)
	assert.True(t, errors.Is(err, domain.ErrNotFound))
	assert.Nil(t, conf)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}


func TestConferenceService_CreateConference_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	accSID := "ACcreate"
	confName := "NewRoom"
	confSID := "CFnewSID"

	// GORM's Create uses a single INSERT statement.
	// It doesn't use RETURNING for all fields by default unless specific tags or GORM features are used.
	// The current implementation of CreateConference in service uses GORM Create directly.
	// GORM populates the passed struct with ID, CreatedAt, UpdatedAt. StartTime remains nil.

	// Mock GORM's behavior for Create: Begin, Insert, Commit
	dbMock.ExpectBegin()
	// The actual SQL generated by GORM for INSERT might vary slightly in argument order or exact fields if some are auto-set.
	// Using sqlmock.AnyArg() for auto-filled fields like created_at, updated_at, id.
	// The query will be something like: INSERT INTO "conferences" ("sid","account_sid","friendly_name","status","start_time","end_time","created_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id"
	// We need to match the query GORM generates. This is a common pain point with sqlmock & GORM.
	// For simplicity, we'll expect any INSERT on "conferences".
	dbMock.ExpectQuery(`INSERT INTO "conferences"`). // More generic match
		WithArgs(confSID, accSID, confName, domain.ConferenceStatusInit, sqlmock.AnyArg(), sqlmock.AnyArg(), nil, nil). // Match main fields, others are auto
		WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1)) // GORM needs ID back for the struct
	dbMock.ExpectCommit()

	conf, err := service.CreateConference(context.Background(), accSID, confName, confSID)

	assert.NoError(t, err)
	assert.NotNil(t, conf)
	assert.Equal(t, confSID, conf.SID)
	assert.Equal(t, domain.ConferenceStatusInit, conf.Status)
	assert.NotZero(t, conf.ID) // ID should be populated by GORM
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_CreateConference_ConflictSID(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	accSID := "ACconflict"
	confName := "ExistingRoom"
	confSID := "CFexistingSID"

	dbMock.ExpectBegin()
	// Simulate unique constraint violation from DB
	// The error string for unique violation in PostgreSQL: "ERROR: duplicate key value violates unique constraint \"conferences_sid_key\" (SQLSTATE 23505)"
	dbMock.ExpectQuery(`INSERT INTO "conferences"`).
		WillReturnError(errors.New("ERROR: duplicate key value violates unique constraint \"conferences_sid_key\" (SQLSTATE 23505)"))
	dbMock.ExpectRollback() // GORM should rollback on error

	conf, err := service.CreateConference(context.Background(), accSID, confName, confSID)

	assert.Error(t, err)
	assert.True(t, errors.Is(err, domain.ErrConflict), "Expected domain.ErrConflict")
	assert.Nil(t, conf)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}


func TestConferenceService_GetOrCreateConference_CreatesNew(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	accSID := "ACgetcreate"
	confName := "MyDynamicRoom"

	// 1. GetConferenceByName returns ErrNotFound
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conferences" WHERE account_sid = $1 AND friendly_name = $2 AND status != $3 ORDER BY created_at DESC LIMIT 1`)).
		WithArgs(accSID, confName, domain.ConferenceStatusCompleted).
		WillReturnError(gorm.ErrRecordNotFound)

	// 2. CreateConference is called
	dbMock.ExpectBegin()
	// Using sqlmock.AnyArg() for SID because it's generated internally by GenerateSID
	dbMock.ExpectQuery(`INSERT INTO "conferences"`).
		WithArgs(mock.MatchedBy(func(sid string) bool { return strings.HasPrefix(sid, "CF") }), accSID, confName, domain.ConferenceStatusInit, sqlmock.AnyArg(), sqlmock.AnyArg(), nil, nil).
		WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1))
	dbMock.ExpectCommit()

	conf, err := service.GetOrCreateConference(context.Background(), accSID, confName)
	assert.NoError(t, err)
	assert.NotNil(t, conf)
	assert.Equal(t, confName, conf.FriendlyName)
	assert.True(t, strings.HasPrefix(conf.SID, "CF"))
	assert.Equal(t, domain.ConferenceStatusInit, conf.Status) // CreateConference sets it to Init
	assert.NoError(t, dbMock.ExpectationsWereMet())
}


func TestConferenceService_GetOrCreateConference_ReturnsExistingActive(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	accSID := "ACgetexisting"
	confName := "ExistingActiveRoom"
	existingConfSID := "CFexistingActive"

	mockExistingConf := domain.Conference{
		ID: 1, SID: existingConfSID, AccountSID: accSID, FriendlyName: confName,
		Status: domain.ConferenceStatusInProgress, /* ... other fields ... */
	}

	rows := sqlmock.NewRows([]string{"id", "sid", "account_sid", "friendly_name", "status"}).
		AddRow(mockExistingConf.ID, mockExistingConf.SID, mockExistingConf.AccountSID, mockExistingConf.FriendlyName, mockExistingConf.Status)

	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conferences" WHERE account_sid = $1 AND friendly_name = $2 AND status != $3 ORDER BY created_at DESC LIMIT 1`)).
		WithArgs(accSID, confName, domain.ConferenceStatusCompleted).
		WillReturnRows(rows)

	conf, err := service.GetOrCreateConference(context.Background(), accSID, confName)
	assert.NoError(t, err)
	assert.NotNil(t, conf)
	assert.Equal(t, existingConfSID, conf.SID)
	assert.Equal(t, domain.ConferenceStatusInProgress, conf.Status) // Should remain in-progress
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_GetOrCreateConference_UpdatesInitToInProgress(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	accSID := "ACinitToProgress"
	confName := "InitRoom"
	existingConfSID := "CFinitRoom"

	mockExistingConf := domain.Conference{
		ID: 1, SID: existingConfSID, AccountSID: accSID, FriendlyName: confName,
		Status: domain.ConferenceStatusInit, CreatedAt: time.Now().Add(-time.Minute), UpdatedAt: time.Now().Add(-time.Minute),
	}

	rows := sqlmock.NewRows([]string{"id", "sid", "account_sid", "friendly_name", "status", "created_at", "updated_at"}).
		AddRow(mockExistingConf.ID, mockExistingConf.SID, mockExistingConf.AccountSID, mockExistingConf.FriendlyName, mockExistingConf.Status, mockExistingConf.CreatedAt, mockExistingConf.UpdatedAt)

	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conferences" WHERE account_sid = $1 AND friendly_name = $2 AND status != $3 ORDER BY created_at DESC LIMIT 1`)).
		WithArgs(accSID, confName, domain.ConferenceStatusCompleted).
		WillReturnRows(rows)

	// Expect update
	dbMock.ExpectBegin()
	// GORM's Updates for map[string]interface{} generates specific SQL
	// Example: UPDATE "conferences" SET "start_time"=$1,"status"=$2,"updated_at"=$3 WHERE sid = $4 AND status = $5
	// Order of SET clauses can vary. Using .* for more flexible matching of the SET part.
	dbMock.ExpectExec(regexp.QuoteMeta(`UPDATE "conferences" SET `) + `.*` + regexp.QuoteMeta(` WHERE sid = $`)). // Match $4 or $5 based on GORM
		WithArgs(domain.ConferenceStatusInProgress, sqlmock.AnyArg(), sqlmock.AnyArg(), existingConfSID, domain.ConferenceStatusInit).
		WillReturnResult(sqlmock.NewResult(0, 1)) // 1 row affected
	dbMock.ExpectCommit()

	conf, err := service.GetOrCreateConference(context.Background(), accSID, confName)
	assert.NoError(t, err)
	assert.NotNil(t, conf)
	assert.Equal(t, existingConfSID, conf.SID)
	assert.Equal(t, domain.ConferenceStatusInProgress, conf.Status)
	assert.NotNil(t, conf.StartTime)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}


// Add similar tests for:
// UpdateConferenceStatus_Success, UpdateConferenceStatus_NotFound
// EndConference_Success, EndConference_NotFound
// AddParticipant_Success, AddParticipant_Conflict, AddParticipant_DBError
// GetParticipant_Success, GetParticipant_NotFound
// GetParticipantByCallSID_Success, GetParticipantByCallSID_NotFound
// UpdateParticipantMuteStatus_Success, UpdateParticipantMuteStatus_NotFound
// UpdateParticipantModeratorStatus_Success, UpdateParticipantModeratorStatus_NotFound
// RemoveParticipant_Success, RemoveParticipant_NotFoundOrAlreadyLeft
// ListParticipants_Success, ListParticipants_Empty

func TestConferenceService_UpdateConferenceStatus_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	confSID := "CFupdatestatus"

	dbMock.ExpectBegin()
	dbMock.ExpectExec(regexp.QuoteMeta(`UPDATE "conferences" SET "status"=$1,"updated_at"=$2 WHERE sid = $3`)).
		WithArgs(domain.ConferenceStatusInProgress, sqlmock.AnyArg(), confSID).
		WillReturnResult(sqlmock.NewResult(0, 1)) // 1 row affected
	dbMock.ExpectCommit()

	err := service.UpdateConferenceStatus(context.Background(), confSID, domain.ConferenceStatusInProgress)
	assert.NoError(t, err)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_EndConference_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	confSID := "CFendconf"
	endTime := time.Now().UTC()

	dbMock.ExpectBegin()
	dbMock.ExpectExec(regexp.QuoteMeta(`UPDATE "conferences" SET "status"=$1,"end_time"=$2,"updated_at"=$3 WHERE sid = $4`)).
		WithArgs(domain.ConferenceStatusCompleted, endTime, sqlmock.AnyArg(), confSID).
		WillReturnResult(sqlmock.NewResult(0, 1))
	dbMock.ExpectCommit()

	err := service.EndConference(context.Background(), confSID, endTime)
	assert.NoError(t, err)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_AddParticipant_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	confSID := "CFaddpart"
	callSID := "CAcall1"
	pSID := "CPpart1"
	accSID := "ACforpart"

	dbMock.ExpectBegin()
	// GORM might list fields in a different order than struct, use .* for flexibility or list them all.
	// Example: INSERT INTO "conference_participants" ("sid","conference_sid","call_sid","account_sid","is_muted","is_moderator","join_time","leave_time") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id"
	dbMock.ExpectQuery(`INSERT INTO "conference_participants"`).
		WithArgs(pSID, confSID, callSID, accSID, false, false, sqlmock.AnyArg(), nil). // is_muted, is_moderator, join_time, leave_time (nil)
		WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1))
	dbMock.ExpectCommit()

	part, err := service.AddParticipant(context.Background(), confSID, callSID, pSID, accSID, false, false)
	assert.NoError(t, err)
	assert.NotNil(t, part)
	assert.Equal(t, pSID, part.SID)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_AddParticipant_Conflict(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())

	confSID := "CFaddpartConflict"
	callSID := "CAcallConflict"
	pSID := "CPpartConflict"
	accSID := "ACforpartConflict"

	dbMock.ExpectBegin()
	dbMock.ExpectQuery(`INSERT INTO "conference_participants"`).
		WillReturnError(errors.New("ERROR: duplicate key value violates unique constraint \"conference_participants_call_sid_key\""))
	dbMock.ExpectRollback()

	// Mock for the fallback GetParticipantByCallSID
	// Assume it finds no active participant (ErrNotFound), so the conflict is treated as a hard conflict.
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conference_participants" WHERE call_sid = $1 AND leave_time IS NULL`)).
		WithArgs(callSID).
		WillReturnError(gorm.ErrRecordNotFound)

	part, err := service.AddParticipant(context.Background(), confSID, callSID, pSID, accSID, false, false)
	assert.Error(t, err)
	assert.True(t, errors.Is(err, domain.ErrConflict))
	assert.Nil(t, part)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}


func TestConferenceService_GetParticipant_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	pSID := "CPgetpart"

	rows := sqlmock.NewRows([]string{"id", "sid", "conference_sid", "call_sid"}).AddRow(1, pSID, "CFconf1", "CAcall1")
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conference_participants" WHERE sid = $1`)).
		WithArgs(pSID).WillReturnRows(rows)

	part, err := service.GetParticipant(context.Background(), pSID)
	assert.NoError(t, err); assert.NotNil(t, part); assert.Equal(t, pSID, part.SID)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_GetParticipantByCallSID_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	callSID := "CAgetpartbycall"

	rows := sqlmock.NewRows([]string{"id", "sid", "conference_sid", "call_sid"}).AddRow(1, "CPpart2", "CFconf2", callSID)
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conference_participants" WHERE call_sid = $1 AND leave_time IS NULL`)).
		WithArgs(callSID).WillReturnRows(rows)

	part, err := service.GetParticipantByCallSID(context.Background(), callSID)
	assert.NoError(t, err); assert.NotNil(t, part); assert.Equal(t, callSID, part.CallSID)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_UpdateParticipantMuteStatus_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	pSID := "CPmute"

	dbMock.ExpectBegin()
	dbMock.ExpectExec(regexp.QuoteMeta(`UPDATE "conference_participants" SET "is_muted"=$1 WHERE sid = $2 AND leave_time IS NULL`)).
		WithArgs(true, pSID).WillReturnResult(sqlmock.NewResult(0,1))
	dbMock.ExpectCommit()

	err := service.UpdateParticipantMuteStatus(context.Background(), pSID, true)
	assert.NoError(t, err)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_RemoveParticipant_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	pSID := "CPremove"
	leaveTime := time.Now().UTC()

	dbMock.ExpectBegin()
	dbMock.ExpectExec(regexp.QuoteMeta(`UPDATE "conference_participants" SET "leave_time"=$1 WHERE sid = $2 AND leave_time IS NULL`)).
		WithArgs(leaveTime, pSID).WillReturnResult(sqlmock.NewResult(0,1))
	dbMock.ExpectCommit()

	err := service.RemoveParticipant(context.Background(), pSID, leaveTime)
	assert.NoError(t, err)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_ListParticipants_Success(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	confSID := "CFlist"

	rows := sqlmock.NewRows([]string{"id", "sid"}).AddRow(1, "CP1").AddRow(2, "CP2")
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conference_participants" WHERE conference_sid = $1 AND leave_time IS NULL`)).
		WithArgs(confSID).WillReturnRows(rows)

	parts, err := service.ListParticipants(context.Background(), confSID)
	assert.NoError(t, err)
	assert.Len(t, parts, 2)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}

func TestConferenceService_ListParticipants_Empty(t *testing.T) {
	gormDB, dbMock := setupConferenceMockDB(t)
	service := services.NewConferenceService(gormDB, newConferenceTestLogger())
	confSID := "CFempty"

	rows := sqlmock.NewRows([]string{"id", "sid"}) // No rows added
	dbMock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "conference_participants" WHERE conference_sid = $1 AND leave_time IS NULL`)).
		WithArgs(confSID).WillReturnRows(rows)

	parts, err := service.ListParticipants(context.Background(), confSID)
	assert.NoError(t, err)
	assert.Len(t, parts, 0)
	assert.NoError(t, dbMock.ExpectationsWereMet())
}


func TestMain(m *testing.M) {
	// Setup global test things if needed
	m.Run()
}
