package services

import (
	"errors"
	"fmt"
	"strings"

	"github.com/user/agbaravoip_golang/internal/domain"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"
	"github.com/sirupsen/logrus"
)

var (
	ErrAccountNotFound      = errors.New("account not found")
	ErrValidationFailed     = errors.New("validation failed")
	ErrHashingFailed        = errors.New("failed to hash auth token")
	ErrSubAccountNotAllowed = errors.New("master account required to create subaccount, or parent account not found")
	ErrInvalidCredentials   = errors.New("invalid credentials")
	ErrUpdateFailed         = errors.New("account update failed")
	ErrDuplicateSID         = errors.New("account SID already exists") // Should be rare due to UUID
)

// AccountService provides methods for account management.
type AccountService struct {
	db     *gorm.DB
	logger *logrus.Entry
}

// NewAccountService creates a new AccountService.
func NewAccountService(db *gorm.DB, logger *logrus.Logger) *AccountService {
	return &AccountService{
		db:     db,
		logger: logger.WithField("service", "account"),
	}
}

// hashAuthToken generates a bcrypt hash of the auth token.
func hashAuthToken(authToken string) (string, error) {
	if authToken == "" {
		return "", fmt.Errorf("%w: auth token cannot be empty for hashing", ErrValidationFailed)
	}
	hashedToken, err := bcrypt.GenerateFromPassword([]byte(authToken), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrHashingFailed, err)
	}
	return string(hashedToken), nil
}

// checkAuthToken compares a plain text auth token with a stored bcrypt hash.
func checkAuthToken(hashedToken, plainToken string) bool {
	if plainToken == "" { // Cannot compare against an empty plain token
		return false
	}
	err := bcrypt.CompareHashAndPassword([]byte(hashedToken), []byte(plainToken))
	return err == nil
}

// CreateMasterAccount creates a new master account.
// AuthToken is expected to be plain text and will be hashed.
func (s *AccountService) CreateMasterAccount(friendlyName string, authToken string) (*domain.Account, error) {
	s.logger.Debugf("Attempting to create master account with FriendlyName: %s", friendlyName)
	if strings.TrimSpace(authToken) == "" {
		s.logger.Error("Auth token cannot be empty for CreateMasterAccount")
		return nil, fmt.Errorf("%w: auth token is required", ErrValidationFailed)
	}

	hashedToken, err := hashAuthToken(authToken)
	if err != nil {
		s.logger.Errorf("Failed to hash auth token for new master account: %v", err)
		return nil, err 
	}

	account := &domain.Account{
		FriendlyName:    friendlyName,
		HashedAuthToken: hashedToken,
		Type:            domain.AccountTypeTrial, 
		Status:          domain.AccountStatusActive,
		ParentSID:       nil, 
	}
	// SID is generated by BeforeCreate hook

	if err := s.db.Create(account).Error; err != nil {
		s.logger.Errorf("Error creating master account in DB: %v", err)
		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
             return nil, fmt.Errorf("%w: %v", ErrDuplicateSID, err)
        }
		return nil, fmt.Errorf("could not create master account: %w", err)
	}
	s.logger.Infof("Master account created successfully: %s", account.SID)
	return account, nil
}

// CreateSubAccount creates a new sub-account under a given parent account.
// AuthToken is expected to be plain text and will be hashed.
func (s *AccountService) CreateSubAccount(parentAccountSid string, friendlyName string, authToken string) (*domain.Account, error) {
	s.logger.Debugf("Attempting to create sub-account for ParentSID: %s, FriendlyName: %s", parentAccountSid, friendlyName)
	if strings.TrimSpace(authToken) == "" {
		s.logger.Error("Auth token cannot be empty for CreateSubAccount")
		return nil, fmt.Errorf("%w: auth token is required", ErrValidationFailed)
	}
	if strings.TrimSpace(parentAccountSid) == "" {
		s.logger.Error("ParentAccountSid cannot be empty for CreateSubAccount")
		return nil, fmt.Errorf("%w: parent account SID is required", ErrValidationFailed)
	}

	// Verify parent account exists and is a master account (or allowed to have subaccounts)
	var parentAccount domain.Account
	if err := s.db.Where("sid = ?", parentAccountSid).First(&parentAccount).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			s.logger.Warnf("Parent account %s not found for creating sub-account", parentAccountSid)
			return nil, fmt.Errorf("%w: parent account %s not found", ErrSubAccountNotAllowed, parentAccountSid)
		}
		s.logger.Errorf("Error fetching parent account %s: %v", parentAccountSid, err)
		return nil, fmt.Errorf("could not verify parent account: %w", err)
	}
	// Add any specific rules here, e.g., if only master accounts (ParentSID is nil) can have subaccounts.
	// For now, any account can be a parent.

	hashedToken, err := hashAuthToken(authToken)
	if err != nil {
		s.logger.Errorf("Failed to hash auth token for new sub-account: %v", err)
		return nil, err
	}

	subAccount := &domain.Account{
		ParentSID:       &parentAccountSid,
		FriendlyName:    friendlyName,
		HashedAuthToken: hashedToken,
		Type:            domain.AccountTypeTrial,  // Inherit or set default? For now, default.
		Status:          domain.AccountStatusActive, // Inherit or set default? For now, default.
	}
	// SID is generated by BeforeCreate hook

	if err := s.db.Create(subAccount).Error; err != nil {
		s.logger.Errorf("Error creating sub-account in DB for parent %s: %v", parentAccountSid, err)
		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
             return nil, fmt.Errorf("%w: %v", ErrDuplicateSID, err)
        }
		return nil, fmt.Errorf("could not create sub-account: %w", err)
	}
	s.logger.Infof("Sub-account %s created successfully under parent %s", subAccount.SID, parentAccountSid)
	return subAccount, nil
}

// GetAccountBySID retrieves an account by its public SID.
func (s *AccountService) GetAccountBySID(accountSid string) (*domain.Account, error) {
	s.logger.Debugf("Attempting to get account by SID: %s", accountSid)
	var account domain.Account
	if err := s.db.Where("sid = ?", accountSid).First(&account).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			s.logger.Warnf("Account with SID %s not found", accountSid)
			return nil, ErrAccountNotFound
		}
		s.logger.Errorf("Error fetching account %s from DB: %v", accountSid, err)
		return nil, fmt.Errorf("database error retrieving account: %w", err)
	}
	s.logger.Debugf("Account %s found", account.SID)
	return &account, nil
}

// GetSubAccounts retrieves all sub-accounts for a given parent account SID.
func (s *AccountService) GetSubAccounts(parentAccountSid string) ([]*domain.Account, error) {
	s.logger.Debugf("Attempting to get sub-accounts for ParentSID: %s", parentAccountSid)
	var subAccounts []*domain.Account
	if err := s.db.Where("parent_sid = ?", parentAccountSid).Find(&subAccounts).Error; err != nil {
		s.logger.Errorf("Error fetching sub-accounts for parent %s from DB: %v", parentAccountSid, err)
		return nil, fmt.Errorf("database error retrieving sub-accounts: %w", err)
	}
	s.logger.Debugf("Found %d sub-accounts for parent %s", len(subAccounts), parentAccountSid)
	return subAccounts, nil
}

// UpdateAccount updates an accounts friendly name and/or status.
// Uses pointers for friendlyName and status to distinguish between empty value and not provided.
func (s *AccountService) UpdateAccount(accountSid string, friendlyName *string, statusStr *string) (*domain.Account, error) {
	s.logger.Debugf("Attempting to update account SID: %s", accountSid)
	
	var account domain.Account
	if err := s.db.Where("sid = ?", accountSid).First(&account).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			s.logger.Warnf("Account %s not found for update", accountSid)
			return nil, ErrAccountNotFound
		}
		s.logger.Errorf("Error fetching account %s for update: %v", accountSid, err)
		return nil, fmt.Errorf("could not retrieve account for update: %w", err)
	}

	updateData := make(map[string]interface{})
	if friendlyName != nil {
		if strings.TrimSpace(*friendlyName) == "" {
             s.logger.Warnf("Friendly name update for account %s is empty, not updating.", accountSid)
        } else {
            updateData["friendly_name"] = *friendlyName
            s.logger.Debugf("Updating friendly_name for account %s to: %s", accountSid, *friendlyName)
        }
	}

	if statusStr != nil {
		validStatus, ok := domain.IsValidAccountStatus(*statusStr)
		if !ok {
			s.logger.Warnf("Invalid status value provided for account %s: %s", accountSid, *statusStr)
			return nil, fmt.Errorf("%w: invalid status %s", ErrValidationFailed, *statusStr)
		}
		updateData["status"] = validStatus
		s.logger.Debugf("Updating status for account %s to: %s", accountSid, validStatus)
	}
	
	if len(updateData) == 0 {
		s.logger.Info("No update data provided for account %s. Returning current account.", accountSid)
		return &account, nil // No fields to update
	}

	if err := s.db.Model(&account).Updates(updateData).Error; err != nil {
		s.logger.Errorf("Failed to update account %s in DB: %v", accountSid, err)
		return nil, fmt.Errorf("%w: %v", ErrUpdateFailed, err)
	}

	s.logger.Infof("Account %s updated successfully.", account.SID)
	return &account, nil
}

// ValidateCredentials checks if the provided account SID and auth token are valid.
// Returns the account if valid, otherwise an error.
func (s *AccountService) ValidateCredentials(accountSid string, plainToken string) (*domain.Account, error) {
	s.logger.Debugf("Validating credentials for account SID: %s", accountSid)
	if strings.TrimSpace(plainToken) == "" {
		s.logger.Warnf("Attempt to validate credentials for %s with empty token", accountSid)
		return nil, ErrInvalidCredentials
	}

	account, err := s.GetAccountBySID(accountSid)
	if err != nil {
		// GetAccountBySID already logs, so just return appropriate error
		if errors.Is(err, ErrAccountNotFound) {
			return nil, ErrInvalidCredentials // Obscure whether account exists or token is wrong
		}
		return nil, err // Other DB error
	}

	if account.Status != domain.AccountStatusActive {
		s.logger.Warnf("Authentication attempt for non-active account %s (status: %s)", accountSid, account.Status)
		return nil, fmt.Errorf("%w: account is not active (status: %s)", ErrInvalidCredentials, account.Status)
	}

	if !checkAuthToken(account.HashedAuthToken, plainToken) {
		s.logger.Warnf("Invalid auth token for account SID: %s", accountSid)
		return nil, ErrInvalidCredentials
	}

	s.logger.Infof("Credentials validated successfully for account SID: %s", accountSid)
	return account, nil
}


