package services

import (
	"errors"
	"fmt"
	"strings"

	"github.com/user/agbaravoip_golang/internal/domain"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

var (
	ErrApplicationNotFound = errors.New("application not found")
	ErrAppValidationFailed = errors.New("application validation failed")
)

// ApplicationService provides methods for application management.
type ApplicationService struct {
	db     *gorm.DB
	logger *logrus.Entry
}

// NewApplicationService creates a new ApplicationService.
func NewApplicationService(db *gorm.DB, logger *logrus.Logger) *ApplicationService {
	return &ApplicationService{
		db:     db,
		logger: logger.WithField("service", "application"),
	}
}

// CreateApplication creates a new application for the given account.
func (s *ApplicationService) CreateApplication(accountSid string, app *domain.Application) (*domain.Application, error) {
	s.logger.Debugf("Attempting to create application for AccountSID: %s, App FriendlyName: %s", accountSid, app.FriendlyName)
	if strings.TrimSpace(accountSid) == "" {
		return nil, fmt.Errorf("%w: accountSid is required", ErrAppValidationFailed)
	}
	// Ensure app.AccountSID is set, overriding any client-provided value for security.
	app.AccountSID = accountSid
	
	// SID for the app itself is generated by BeforeCreate hook in domain.Application

	if err := s.db.Create(app).Error; err != nil {
		s.logger.Errorf("Error creating application in DB for AccountSID %s: %v", accountSid, err)
		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
             return nil, fmt.Errorf("application SID or other unique field conflict: %w", err)
        }
		return nil, fmt.Errorf("could not create application: %w", err)
	}
	s.logger.Infof("Application %s created successfully for AccountSID %s", app.SID, accountSid)
	return app, nil
}

// GetApplicationBySID retrieves a specific application by its SID, ensuring it belongs to the account.
func (s *ApplicationService) GetApplicationBySID(accountSid string, appSid string) (*domain.Application, error) {
	s.logger.Debugf("Attempting to get application by SID: %s for AccountSID: %s", appSid, accountSid)
	var app domain.Application
	if err := s.db.Where("sid = ? AND account_sid = ?", appSid, accountSid).First(&app).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			s.logger.Warnf("Application with SID %s not found for AccountSID %s", appSid, accountSid)
			return nil, ErrApplicationNotFound
		}
		s.logger.Errorf("Error fetching application %s for AccountSID %s from DB: %v", appSid, accountSid, err)
		return nil, fmt.Errorf("database error retrieving application: %w", err)
	}
	s.logger.Debugf("Application %s found for AccountSID %s", app.SID, accountSid)
	return &app, nil
}

// ListApplications retrieves all applications for a given account SID.
func (s *ApplicationService) ListApplications(accountSid string) ([]*domain.Application, error) {
	s.logger.Debugf("Attempting to list applications for AccountSID: %s", accountSid)
	var apps []*domain.Application
	if err := s.db.Where("account_sid = ?", accountSid).Find(&apps).Error; err != nil {
		s.logger.Errorf("Error fetching applications for AccountSID %s from DB: %v", accountSid, err)
		return nil, fmt.Errorf("database error retrieving applications: %w", err)
	}
	s.logger.Debugf("Found %d applications for AccountSID %s", len(apps), accountSid)
	return apps, nil
}

// UpdateApplication updates specified fields of an existing application.
// `updates` map contains fields to be updated.
func (s *ApplicationService) UpdateApplication(accountSid string, appSid string, updates map[string]interface{}) (*domain.Application, error) {
	s.logger.Debugf("Attempting to update application SID: %s for AccountSID: %s", appSid, accountSid)

	// First, verify the application exists and belongs to the account.
	app, err := s.GetApplicationBySID(accountSid, appSid)
	if err != nil {
		return nil, err // ErrApplicationNotFound or other DB error
	}

	// Filter updates to only allowed fields if necessary, or validate values.
	// GORM handles partial updates with maps well.
	// Ensure AccountSID and SID are not part of the updates map from client.
	delete(updates, "sid")
	delete(updates, "account_sid")
	delete(updates, "id") // Should not update primary key
	delete(updates, "created_at") // Should not update created_at

	if len(updates) == 0 {
		s.logger.Info("No update data provided for application %s. Returning current application.", appSid)
		return app, nil
	}
	
	// GORM automatically handles updating `updated_at` due to `autoUpdateTime` tag.
	if err := s.db.Model(app).Where("sid = ? AND account_sid = ?", appSid, accountSid).Updates(updates).Error; err != nil {
		s.logger.Errorf("Failed to update application %s in DB: %v", appSid, err)
		return nil, fmt.Errorf("could not update application: %w", err)
	}
	
	// Reload the application to get all updated fields, especially if BeforeUpdate hooks change something.
	// Or, if Updates() returns the updated model, that can be used. GORM v2 does update the passed model.
	s.logger.Infof("Application %s updated successfully for AccountSID %s.", app.SID, accountSid)
	return app, nil // app object should be updated by GORM if Updates was successful on a pointer.
}

// DeleteApplication deletes an application by its SID, ensuring it belongs to the account.
func (s *ApplicationService) DeleteApplication(accountSid string, appSid string) error {
	s.logger.Debugf("Attempting to delete application SID: %s for AccountSID: %s", appSid, accountSid)

	// Verify the application exists and belongs to the account before deleting.
	// This also ensures we are not trying to delete something that does not exist or belongs to someone else.
	var app domain.Application
	if err := s.db.Where("sid = ? AND account_sid = ?", appSid, accountSid).First(&app).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			s.logger.Warnf("Application %s not found for deletion under AccountSID %s", appSid, accountSid)
			return ErrApplicationNotFound
		}
		s.logger.Errorf("Error fetching application %s for deletion: %v", appSid, err)
		return fmt.Errorf("could not retrieve application for deletion: %w", err)
	}
	
	// GORM performs a soft delete if `DeletedAt` field exists in the model.
	if err := s.db.Where("sid = ? AND account_sid = ?", appSid, accountSid).Delete(&domain.Application{}).Error; err != nil {
		s.logger.Errorf("Failed to delete application %s from DB: %v", appSid, err)
		return fmt.Errorf("could not delete application: %w", err)
	}

	s.logger.Infof("Application %s deleted successfully for AccountSID %s.", appSid, accountSid)
	return nil
}


